package persistence.sql.ddl.query;

import jakarta.persistence.GenerationType;
import persistence.sql.definition.TableId;

public class IdentityKeyGenerationStrategy implements PrimaryKeyGenerationStrategy {

    @Override
    public String generatePrimaryKeySQL() {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public boolean supports(TableId pk) {
        return pk.generationType().equals(GenerationType.IDENTITY);
    }
}
